import type { Conversation, Contact } from "./types"

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@acme.com",
    phone: "+15551234567",
    company: "Acme Corp",
    role: "Marketing Director",
    location: "San Francisco, CA",
    status: "Lead",
    online: true,
    tags: ["VIP", "Enterprise", "Marketing"],
    notes: "Interested in our enterprise plan. Follow up about Q1 campaign.",
    recentActivity: [
      { action: "Email opened", date: "Today at 2:30 PM" },
      { action: "Visited pricing page", date: "Yesterday at 11:00 AM" },
      { action: "Downloaded whitepaper", date: "Jan 5, 2026" },
    ],
  },
  {
    id: "2",
    name: "Michael Chen",
    email: "michael.chen@techstart.io",
    phone: "+15552345678",
    company: "TechStart",
    role: "CEO",
    location: "Austin, TX",
    status: "Customer",
    online: false,
    lastSeen: "2 hours ago",
    tags: ["Startup", "Tech", "Priority"],
    notes: "Looking to expand their team. Potential upsell opportunity.",
    recentActivity: [
      { action: "Call completed", date: "Today at 10:00 AM" },
      { action: "Invoice paid", date: "Jan 8, 2026" },
    ],
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.r@globalent.com",
    phone: "+15553456789",
    company: "Global Enterprises",
    role: "Operations Manager",
    location: "New York, NY",
    status: "Prospect",
    online: true,
    tags: ["Enterprise", "Operations"],
    notes: "Initial discovery call scheduled for next week.",
    recentActivity: [
      { action: "Form submitted", date: "Today at 9:15 AM" },
      { action: "Website visit", date: "Yesterday" },
    ],
  },
  {
    id: "4",
    name: "David Park",
    email: "david.park@innovate.co",
    phone: "+15554567890",
    company: "Innovate Co",
    role: "Product Manager",
    location: "Seattle, WA",
    status: "Lead",
    online: false,
    lastSeen: "1 day ago",
    tags: ["Product", "SaaS"],
    notes: "",
    recentActivity: [{ action: "Missed call", date: "Yesterday at 3:00 PM" }],
  },
  {
    id: "5",
    name: "Lisa Thompson",
    email: "lisa.t@retail.plus",
    phone: "+15555678901",
    company: "Retail Plus",
    role: "Sales Director",
    location: "Chicago, IL",
    status: "Customer",
    online: true,
    tags: ["Retail", "Sales", "VIP"],
    notes: "Long-term customer. Annual review coming up in February.",
    recentActivity: [
      { action: "Support ticket resolved", date: "Jan 9, 2026" },
      { action: "Renewal reminder sent", date: "Jan 7, 2026" },
    ],
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    phone: "+15551234567",
    lastMessage: "Perfect, I'll send you a calendar invite.",
    time: "10:38 AM",
    unread: true,
    unreadCount: 3,
    online: true,
    type: "message",
    contactId: "1",
    messages: [
      {
        id: "1",
        content: "Hi there! I wanted to follow up on our previous discussion.",
        sender: "contact",
        timestamp: "10:30 AM",
        type: "text",
      },
      {
        id: "2",
        content: "Of course! I've reviewed the proposal.",
        sender: "user",
        timestamp: "10:32 AM",
        type: "text",
      },
      {
        id: "3",
        content: "Can we schedule a call to discuss?",
        sender: "contact",
        timestamp: "10:35 AM",
        type: "text",
      },
      { id: "4", content: "How about tomorrow at 2 PM?", sender: "user", timestamp: "10:36 AM", type: "text" },
      {
        id: "5",
        content: "Perfect, I'll send you a calendar invite.",
        sender: "contact",
        timestamp: "10:38 AM",
        type: "text",
      },
    ],
  },
  {
    id: "2",
    name: "Michael Chen",
    phone: "+15552345678",
    lastMessage: "Call ended - 15 min",
    time: "10:00 AM",
    unread: false,
    online: false,
    type: "call",
    callStatus: "outgoing",
    contactId: "2",
    messages: [
      {
        id: "1",
        content: "Outgoing call",
        sender: "user",
        timestamp: "9:45 AM",
        type: "call_log",
        duration: "15:23",
        callType: "outgoing",
      },
      {
        id: "2",
        content: "Call Recording",
        sender: "user",
        timestamp: "10:00 AM",
        type: "call_recording",
        recordingUrl: "/placeholder-recording.mp3",
        duration: "15:23",
      },
    ],
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    phone: "+15553456789",
    lastMessage: "Thanks for the quick response!",
    time: "9:45 AM",
    unread: true,
    unreadCount: 1,
    online: true,
    type: "message",
    contactId: "3",
    messages: [
      {
        id: "1",
        content: "Hi, I saw your website and I'm interested.",
        sender: "contact",
        timestamp: "9:30 AM",
        type: "text",
      },
      { id: "2", content: "Great to hear! How can I help you?", sender: "user", timestamp: "9:35 AM", type: "text" },
      { id: "3", content: "Thanks for the quick response!", sender: "contact", timestamp: "9:45 AM", type: "text" },
    ],
  },
  {
    id: "4",
    name: "David Park",
    phone: "+15554567890",
    lastMessage: "Missed call",
    time: "Yesterday",
    unread: true,
    unreadCount: 1,
    online: false,
    type: "call",
    callStatus: "missed",
    contactId: "4",
    messages: [
      {
        id: "1",
        content: "Missed call",
        sender: "contact",
        timestamp: "3:00 PM",
        type: "call_log",
        callType: "missed",
      },
    ],
  },
  {
    id: "5",
    name: "Lisa Thompson",
    phone: "+15555678901",
    lastMessage: "The new feature looks great!",
    time: "Yesterday",
    unread: false,
    online: true,
    type: "message",
    contactId: "5",
    messages: [
      {
        id: "1",
        content: "Just wanted to check in on the new feature.",
        sender: "contact",
        timestamp: "2:00 PM",
        type: "text",
      },
      { id: "2", content: "We just released it! Check it out.", sender: "user", timestamp: "2:15 PM", type: "text" },
      { id: "3", content: "The new feature looks great!", sender: "contact", timestamp: "2:30 PM", type: "text" },
    ],
  },
]
